import Head from 'next/head'
import { useRouter } from 'next/router';
import { useLayoutEffect } from 'react';
import Header from '../layout/Header'
import Navigation from '../layout/Navigation'

const Home = () => {

  const router = useRouter();

  useLayoutEffect(() => {
    const user = localStorage["user"];
    if (!user)
      router.replace("/auth-login");
  })

  return (
    <>
      <Head>
        <title>Muhasebe App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Header />
        {/*== BODY CONTNAINER ==*/}
        <div className="container-fluid">
          <div className="row">
            <div className="sb2-1">
              {/*== USER INFO ==*/}
              <div className="sb2-12" style={{ background: "#171717", color: "#fff" }}>
                <ul>
                  <li>
                    <Navigation />
                  </li>
                  <li />
                </ul>
              </div>
            </div>
            <div className="sb2-2">
              <h4>Menüden işlem seçiniz</h4>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}

export default Home;
